/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9 at Sat Apr 14 14:04:49 2018. */

#include "demo.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const cmdId_t msgSayHello_cmdId_default = cmdId_t_SayHello;


const pb_field_t msgSayHello_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, msgSayHello, cmdId, cmdId, &msgSayHello_cmdId_default),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, msgSayHello, msg, cmdId, 0),
    PB_LAST_FIELD
};



/* @@protoc_insertion_point(eof) */
