# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='demo.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\ndemo.proto\"=\n\x0bmsgSayHello\x12!\n\x05\x63mdId\x18\x01 \x02(\x0e\x32\x08.cmdId_t:\x08SayHello\x12\x0b\n\x03msg\x18\x02 \x02(\t*\x17\n\x07\x63mdId_t\x12\x0c\n\x08SayHello\x10\x00')
)

_CMDID_T = _descriptor.EnumDescriptor(
  name='cmdId_t',
  full_name='cmdId_t',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SayHello', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=77,
  serialized_end=100,
)
_sym_db.RegisterEnumDescriptor(_CMDID_T)

cmdId_t = enum_type_wrapper.EnumTypeWrapper(_CMDID_T)
SayHello = 0



_MSGSAYHELLO = _descriptor.Descriptor(
  name='msgSayHello',
  full_name='msgSayHello',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmdId', full_name='msgSayHello.cmdId', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='msgSayHello.msg', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=75,
)

_MSGSAYHELLO.fields_by_name['cmdId'].enum_type = _CMDID_T
DESCRIPTOR.message_types_by_name['msgSayHello'] = _MSGSAYHELLO
DESCRIPTOR.enum_types_by_name['cmdId_t'] = _CMDID_T
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

msgSayHello = _reflection.GeneratedProtocolMessageType('msgSayHello', (_message.Message,), dict(
  DESCRIPTOR = _MSGSAYHELLO,
  __module__ = 'demo_pb2'
  # @@protoc_insertion_point(class_scope:msgSayHello)
  ))
_sym_db.RegisterMessage(msgSayHello)


# @@protoc_insertion_point(module_scope)
